services:
  migrate:
    build: .
    image: rest-api:${VERSION:-latest}
    command: flask db upgrade
    env_file:
      - .env
    volumes:
      - sqlite-data:/app/instance

  rest-api:
    build: .
    image: rest-api:${VERSION:-latest}
    ports:
      - "5000:5000"
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - sqlite-data:/app/instance

volumes:
  sqlite-data:
