apiVersion: v1
kind: Namespace
metadata:
  name: student-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: student-api
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: student-api
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: student-api
          serviceAccountRef:
            name: external-secrets-vault
            audiences:
              - vault
