apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - external-secrets-application.yaml
  - vault-application.yaml
  - stack-application.yaml
  - observability-application.yaml
