apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bootcamp
  namespace: argocd
spec:
  description: One2N SRE bootcamp applications
  sourceRepos:
    - https://github.com/gotenksIN/one2n_sre_bootcamp.git
  destinations:
    - namespace: app
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
