apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bootcamp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  description: One2N SRE bootcamp applications
  sourceRepos:
    - https://github.com/gotenksIN/one2n_sre_bootcamp.git
  destinations:
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
    - namespace: student-api
      server: https://kubernetes.default.svc
    - namespace: observability
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
