apiVersion: v1
kind: Secret
metadata:
  name: bootcamp-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/gotenksIN/one2n_sre_bootcamp.git
  username: <your-github-username>
  password: <your-github-token-or-pat>
