apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bootcamp
  source:
    repoURL: https://github.com/gotenksIN/one2n_sre_bootcamp.git
    targetRevision: master
    path: helm/vault
    helm:
      releaseName: vault
      valueFiles:
        - values.yaml
        - values-demo.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
