apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  FLASK_DEBUG: {{ .Values.config.flaskDebug | quote }}
