apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecrets.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
