apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  labels:
    {{- include "observability.labels" . | nindent 4 }}
data:
  config.alloy: |
    discovery.kubernetes "pods" {
      role = "pod"
    }

    discovery.relabel "student_api" {
      targets = discovery.kubernetes.pods.targets

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        action = "keep"
        regex = "student-api"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_instance"]
        action = "keep"
        regex = "stack"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        action = "keep"
        regex = "stack"
      }

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label = "namespace"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label = "pod"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label = "container"
      }
    }

    loki.source.kubernetes "student_api" {
      targets    = discovery.relabel.student_api.output
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://{{ .Release.Name }}-loki-gateway.{{ .Release.Namespace }}.svc.cluster.local/loki/api/v1/push"
      }
    }
